'use client';
import {useState} from 'react';
import {useQuery,useInfiniteQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {Users,Wallet,CheckCircle2,Phone} from 'lucide-react';
import {toast} from 'sonner';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {api,money,time} from '@/lib/api';
import {useLanguage} from '@/lib/i18n';
import {RouteLine,TripTime,Status,LoadingCards,ErrorState,Empty} from './shared';
import type {UserDTO,DepartureDTO,BookingDTO,DeparturePageDTO} from '@saathi/contracts';
export function DriverView({user,view}:{user:UserDTO;view:string}){
  const {t}=useLanguage();const qc=useQueryClient();const [noShowConfirm,setNoShowConfirm]=useState<string|null>(null);const [manifestId,setManifestId]=useState<string|null>(null);const [confirmation,setConfirmation]=useState<{trip:DepartureDTO;action:string}|null>(null);
  const history=view==='history';
  const tripPages=useInfiniteQuery({queryKey:['driver-trips',user.id,history],queryFn:({pageParam})=>api<DeparturePageDTO>(`/driver/trips?history=${history}&page=${pageParam}&limit=30`),initialPageParam:1,getNextPageParam:last=>last.hasMore?last.page+1:undefined,refetchInterval:15000});
  const overview=useQuery({queryKey:['driver',user.id],queryFn:()=>api<{trips:DepartureDTO[];collectedPaise:number;completedTrips:number}>('/driver/overview'),refetchInterval:15000});
  const manifest=useQuery({queryKey:['manifest',user.id,manifestId],queryFn:()=>api<{departure:DepartureDTO;bookings:BookingDTO[]}>(`/driver/trips/${manifestId}/manifest`),enabled:!!manifestId,refetchInterval:manifestId?15000:false});
  const action=useMutation({mutationFn:({id,action}:{id:string;action:string})=>api(`/driver/trips/${id}/${action}`,{method:'POST',body:{}}),onSuccess:(_,variables)=>{qc.invalidateQueries({queryKey:['driver',user.id]});qc.invalidateQueries({queryKey:['driver-trips',user.id]});qc.invalidateQueries({queryKey:['manifest',user.id]});setConfirmation(null);toast.success(t(({accept:'Trip accepted',decline:'Trip declined',start:'Trip started',complete:'Trip completed'} as Record<string,string>)[variables.action]));},onError:e=>toast.error(e.message)});
  const collect=useMutation({mutationFn:(id:string)=>api(`/driver/bookings/${id}/collect`,{method:'POST',body:{}}),onSuccess:()=>{qc.invalidateQueries({queryKey:['driver',user.id]});qc.invalidateQueries({queryKey:['driver-trips',user.id]});qc.invalidateQueries({queryKey:['manifest',user.id]});toast.success(t('Cash recorded'));},onError:e=>toast.error(e.message)});
  const noShow=useMutation({mutationFn:(id:string)=>api(`/driver/bookings/${id}/no-show`,{method:'POST',body:{}}),onSuccess:()=>{qc.invalidateQueries({queryKey:['manifest',user.id]});setNoShowConfirm(null);toast.success(t('No show recorded'));},onError:e=>toast.error(e.message)});
  const trips=tripPages.data?.pages.flatMap(p=>p.departures)||[];
  return <><div className="page-heading"><div className="eyebrow">{t('Driver')} / {user.name}</div><h1>{t(view==='history'?'History':'Your trips')}</h1><p>{t('Today’s work, in one place.')}</p></div><div className="stat-strip"><div className="stat"><p>{t('Cash collected')}</p><strong>{money(overview.data?.collectedPaise||0)}</strong></div><div className="stat"><p>{t('Completed trips')}</p><strong>{overview.data?.completedTrips||0}</strong></div></div>{tripPages.isPending?<LoadingCards/>:tripPages.error?<ErrorState error={tripPages.error} retry={()=>tripPages.refetch()}/>:trips.length?<div className="list-grid trip-grid">{trips.map(d=><article className="trip-card" key={d.id}><header><strong className="departure-time">{time(d.departureAt)}</strong><Status value={d.status==='scheduled'?d.assignment:d.status}/></header><RouteLine departure={d}/><TripTime departure={d}/><div className="driver-meta"><Users size={16}/>{d.bookedSeats} {t('Seats reserved')} • {d.vehicle}</div><footer>{d.status==='scheduled'&&d.assignment==='pending'?<><Button disabled={action.isPending} onClick={()=>action.mutate({id:d.id,action:'accept'})}>{t('Accept trip')}</Button><Button variant="outline" disabled={action.isPending} onClick={()=>setConfirmation({trip:d,action:'decline'})}>{t('Decline trip')}</Button></>:<>{d.assignment!=='declined'&&<Button variant="outline" onClick={()=>setManifestId(d.id)}><Users size={16}/>{t('Passenger list')}</Button>}{d.status==='scheduled'&&d.assignment==='accepted'&&<Button disabled={new Date(d.departureAt).getTime()-Date.now()>15*60000} onClick={()=>setConfirmation({trip:d,action:'start'})}>{t('Start trip')}</Button>}{d.status==='in-progress'&&<Button onClick={()=>setConfirmation({trip:d,action:'complete'})}>{t('Complete trip')}</Button>}</>}</footer>{d.status==='scheduled'&&d.assignment==='accepted'&&new Date(d.departureAt).getTime()-Date.now()>15*60000&&<p className="text-xs mt-3">{t('Trips can start 15 minutes before departure.')}</p>}</article>)}</div>:<Empty title={view==='history'?'No history yet':'No assigned trips'} description="Your operator will assign upcoming trips here."/>}
  {tripPages.hasNextPage&&<Button variant="outline" className="mt-5" onClick={()=>tripPages.fetchNextPage()} disabled={tripPages.isFetchingNextPage}>{t('Load more')}</Button>}
  <Dialog open={!!manifestId} onOpenChange={o=>!o&&setManifestId(null)}><DialogContent className="max-h-[85dvh] overflow-y-auto"><DialogHeader><DialogTitle>{t('Passenger list')}</DialogTitle><DialogDescription>{manifest.data?`${t(manifest.data.departure.pickup)} — ${t(manifest.data.departure.destination)}`:t('Trip details')}</DialogDescription></DialogHeader>{manifest.isPending?<LoadingCards/>:manifest.error?<ErrorState error={manifest.error} retry={()=>manifest.refetch()}/>:manifest.data?.bookings.length?<div>{manifest.data.bookings.map(b=><div className="manifest-row" key={b.id}><div><strong>{b.passengerName}</strong><p>{b.seats} {t('Seats')} • {money(b.totalPaise)}</p><p>{b.reference}</p>{b.contactPhone&&<a className="text-sm inline-flex items-center gap-1 mt-1 text-green-800" href={`tel:${b.contactPhone}`}><Phone size={13}/>{b.contactPhone}</a>}</div>{b.status==='no-show'?<Status value="no-show"/>:b.cashCollected?<span className="flex items-center gap-1 text-sm text-green-800"><CheckCircle2 size={17}/>{t('Collected')}</span>:<div className="grid gap-2"><Button variant="outline" disabled={collect.isPending||manifest.data?.departure.status==='scheduled'} onClick={()=>collect.mutate(b.id)}><Wallet size={16}/>{t('Record cash')}</Button>{manifest.data?.departure.status==='in-progress'&&<Button variant="ghost" disabled={noShow.isPending} onClick={()=>noShowConfirm===b.id?noShow.mutate(b.id):setNoShowConfirm(b.id)}>{t(noShowConfirm===b.id?'Confirm no show':'Mark no show')}</Button>}</div>}</div>)}</div>:<Empty title="No passengers booked"/>}</DialogContent></Dialog>
  <AlertDialog open={!!confirmation} onOpenChange={o=>{if(!o&&!action.isPending)setConfirmation(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t(({decline:'Decline trip',start:'Start trip',complete:'Complete trip'} as Record<string,string>)[confirmation?.action||'start'])}</AlertDialogTitle><AlertDialogDescription>{confirmation&&`${t(confirmation.trip.pickup)} — ${t(confirmation.trip.destination)}. `}{t('This action cannot be undone.')}</AlertDialogDescription></AlertDialogHeader>{action.error&&<p className="form-error">{action.error.message}</p>}<AlertDialogFooter><AlertDialogCancel disabled={action.isPending}>{t('Cancel')}</AlertDialogCancel><AlertDialogAction disabled={action.isPending} onClick={e=>{e.preventDefault();if(confirmation)action.mutate({id:confirmation.trip.id,action:confirmation.action});}}>{t(({decline:'Decline trip',start:'Start trip',complete:'Complete trip'} as Record<string,string>)[confirmation?.action||'start'])}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </>;
}
