'use client';
import {useState,useEffect} from 'react';
import {useQuery,useInfiniteQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {Plus,Users,BusFront,MapPin,Pencil} from 'lucide-react';
import {toast} from 'sonner';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Badge} from '@/components/ui/badge';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {api,money,time,date,localDateTime} from '@/lib/api';
import {useLanguage} from '@/lib/i18n';
import {Picker,RouteLine,TripTime,Status,LoadingCards,ErrorState,Empty} from './shared';
import type {UserDTO,OverviewDTO,DepartureDTO,DriverDTO,RouteDTO,StopDTO,DeparturePageDTO} from '@saathi/contracts';
type Modal={type:'departure'}|{type:'assign';record:DepartureDTO}|{type:'driver';record?:DriverDTO}|{type:'route';record?:RouteDTO}|{type:'stop';record?:StopDTO};
export function OperatorView({user,view}:{user:UserDTO;view:string}){
  const {t}=useLanguage();const qc=useQueryClient();const [modal,setModal]=useState<Modal|null>(null);const [history,setHistory]=useState(false);const [cancel,setCancel]=useState<DepartureDTO|null>(null);
  const overview=useQuery({queryKey:['operator',user.id],queryFn:()=>api<OverviewDTO>('/operator/overview'),refetchInterval:20000});
  const tripPages=useInfiniteQuery({queryKey:['operator-departures',user.id,history],queryFn:({pageParam})=>api<DeparturePageDTO>(`/operator/departures?history=${history}&page=${pageParam}&limit=30`),initialPageParam:1,getNextPageParam:last=>last.hasMore?last.page+1:undefined,enabled:view==='departures',refetchInterval:view==='departures'?20000:false});
  const departures=tripPages.data?.pages.flatMap(p=>p.departures)||[];
  const refresh=()=>{qc.invalidateQueries({queryKey:['operator',user.id]});qc.invalidateQueries({queryKey:['operator-departures',user.id]});qc.invalidateQueries({queryKey:['routes']});qc.invalidateQueries({queryKey:['stops']});qc.invalidateQueries({queryKey:['departures']});};
  const cancelMutation=useMutation({mutationFn:()=>api(`/operator/departures/${cancel!.id}/cancel`,{method:'POST',body:{}}),onSuccess:()=>{refresh();setCancel(null);toast.success(t('Departure cancelled'));},onError:e=>toast.error(e.message)});
  const data=overview.data;
  return <><div className="page-heading"><div className="eyebrow">{t('Operator')}</div><h1>{t('Local operations')}</h1><p>{t('Keep your community moving.')}</p></div>
  {data&&<div className="stat-strip four"><div className="stat"><p>{t('Booked seats')}</p><strong>{data.stats.confirmedSeats}</strong></div><div className="stat"><p>{t('Completed trips')}</p><strong>{data.stats.completedTrips}</strong></div><div className="stat"><p>{t('Recorded collections')}</p><strong>{money(data.stats.collectedPaise)}</strong></div><div className="stat"><p>{t('Cancelled bookings')}</p><strong>{data.stats.cancelledBookings}</strong></div></div>}
  {overview.isPending?<LoadingCards/>:overview.error?<ErrorState error={overview.error} retry={()=>overview.refetch()}/>:data&&<>
  {view==='departures'&&<><div className="toolbar"><h2>{t('Departures')}</h2><Button onClick={()=>setModal({type:'departure'})}><Plus size={17}/>{t('New departure')}</Button></div><Tabs value={history?'history':'upcoming'} onValueChange={v=>setHistory(v==='history')} className="segmented"><TabsList className="h-12"><TabsTrigger value="upcoming" className="min-h-10 px-5">{t('Upcoming')}</TabsTrigger><TabsTrigger value="history" className="min-h-10 px-5">{t('History')}</TabsTrigger></TabsList></Tabs>{tripPages.isPending?<LoadingCards/>:tripPages.error?<ErrorState error={tripPages.error} retry={()=>tripPages.refetch()}/>:departures.length?<div className="operator-list">{departures.map(d=><article className="operator-card" key={d.id}><header><strong>{time(d.departureAt)}</strong><Status value={d.status}/></header><RouteLine departure={d} compact/><TripTime departure={d}/><div className="driver-meta"><BusFront size={16}/>{d.driverName||t('Unassigned')}<Status value={d.assignment}/></div><p className="mt-3">{d.bookedSeats}/{d.capacity} {t('Booked seats')} • {money(d.farePaise)} {t('per seat')}</p>{d.status==='scheduled'&&<footer><Button variant="outline" disabled={new Date(d.departureAt)<=new Date()} onClick={()=>setModal({type:'assign',record:d})}>{t('Assign driver')}</Button><Button variant="ghost" onClick={()=>{cancelMutation.reset();setCancel(d);}}>{t('Cancel departure')}</Button></footer>}</article>)}</div>:<Empty title="No departures yet"/>}{tripPages.hasNextPage&&<Button variant="outline" className="mt-5" onClick={()=>tripPages.fetchNextPage()} disabled={tripPages.isFetchingNextPage}>{t('Load more')}</Button>}</>}
  {view==='drivers'&&<><div className="toolbar"><h2>{t('Drivers')}</h2><Button onClick={()=>setModal({type:'driver'})}><Plus size={17}/>{t('Add driver')}</Button></div>{data.drivers.length?<div className="operator-list">{data.drivers.map(d=><article className="operator-card" key={d.id}><header><h3>{d.name}</h3><Badge variant="outline">{t(d.active?'Active':'Inactive')}</Badge></header><p>{d.vehicle} • {d.capacity} {t('Seats')}</p><p className="mt-2">{d.phone}</p><p className="mt-2 break-all">{d.email}</p><div className="mt-3"><Badge variant="outline">{t(d.verified?'Verified':'Unverified')}</Badge></div><footer><Button variant="outline" onClick={()=>setModal({type:'driver',record:d})}><Pencil size={15}/>{t('Save changes')}</Button></footer></article>)}</div>:<Empty title="No drivers yet"/>}</>}
  {view==='routes'&&<><div className="toolbar"><h2>{t('Routes')}</h2><div className="flex gap-2"><Button variant="outline" onClick={()=>setModal({type:'stop'})}>{t('Add stop')}</Button><Button onClick={()=>setModal({type:'route'})}><Plus size={17}/>{t('Add route')}</Button></div></div>{data.routes.length?<div className="operator-list">{data.routes.map(r=><article className="operator-card" key={r.id}><header><h3>{money(r.farePaise)} <span className="text-sm font-normal">{t('per seat')}</span></h3><Badge variant="outline">{t(r.active?'Active':'Inactive')}</Badge></header><RouteLine departure={r} compact/><footer><Button variant="outline" onClick={()=>setModal({type:'route',record:r})}><Pencil size={15}/>{t('Edit route')}</Button></footer></article>)}</div>:<Empty title="No routes yet"/>}<h2 className="mt-8 mb-4">{t('Pickup points')}</h2><div className="operator-list">{data.stops.map(s=><article className="operator-card" key={s.id}><header><h3 className="flex items-center gap-2"><MapPin size={17}/>{t(s.name)}</h3><Badge variant="outline">{t(s.active?'Active':'Inactive')}</Badge></header><p>{t(s.locality)}</p><footer><Button variant="outline" onClick={()=>setModal({type:'stop',record:s})}>{t('Edit stop')}</Button></footer></article>)}</div></>}
  {view==='activity'&&<><h2 className="section-title">{t('Recent activity')}</h2>{data.audit.length?<div className="booking-panel">{data.audit.map(a=><div className="audit-row" key={a.id}><div><strong>{t(({ 'booking.created':'Booking confirmed','booking.cancelled':'Booking cancelled','departure.created':'Departure created','departure.assigned':'Driver assigned','departure.cancelled':'Departure cancelled','cash.collected':'Cash recorded','trip.accept':'Trip accepted','trip.decline':'Trip declined','trip.start':'Trip started','trip.complete':'Trip completed','driver.created':'Driver created','driver.updated':'Changes saved','route.created':'Route created','route.updated':'Changes saved','stop.created':'Stop created','stop.updated':'Changes saved'} as Record<string,string>)[a.action]||a.action)}</strong><p className="text-xs mt-1">{a.entityId.slice(-8)}</p></div><small>{date(a.createdAt)}<br/>{time(a.createdAt)}</small></div>)}</div>:<Empty title="No activity yet"/>}</>}
  {modal&&<OperatorForm modal={modal} data={data} close={()=>setModal(null)} success={refresh}/>}
  </>}
  <AlertDialog open={!!cancel} onOpenChange={o=>{if(!o&&!cancelMutation.isPending)setCancel(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t('Cancel departure')}</AlertDialogTitle><AlertDialogDescription>{t('All confirmed bookings on this departure will be cancelled.')}</AlertDialogDescription></AlertDialogHeader>{cancelMutation.error&&<p className="form-error">{cancelMutation.error.message}</p>}<AlertDialogFooter><AlertDialogCancel disabled={cancelMutation.isPending}>{t('Cancel')}</AlertDialogCancel><AlertDialogAction disabled={cancelMutation.isPending} onClick={e=>{e.preventDefault();cancelMutation.mutate();}}>{t('Cancel departure')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </>;
}
function OperatorForm({modal,data,close,success}:{modal:Modal;data:OverviewDTO;close:()=>void;success:()=>void}){
  const {t}=useLanguage();const [draft,setDraft]=useState<Record<string,string|boolean>>({});
  const isEdit='record'in modal&&!!modal.record;
  useEffect(()=>{
    if(modal.type==='departure')setDraft({routeId:data.routes.find(r=>r.active)?.id||'',driverId:data.drivers.find(d=>d.active&&d.verified)?.userId||'none',departureAt:localDateTime(),durationMinutes:'30',capacity:'4'});
    if(modal.type==='assign')setDraft({driverId:modal.record.driverId||data.drivers.find(d=>d.active&&d.verified)?.userId||''});
    if(modal.type==='driver')setDraft(modal.record?{active:modal.record.active,verified:modal.record.verified}:{name:'',email:'',password:'',phone:'',vehicle:'',capacity:'4',verified:false});
    if(modal.type==='route')setDraft({fromStopId:modal.record?.fromStopId||data.stops[0]?.id||'',toStopId:modal.record?.toStopId||data.stops[1]?.id||'',fare:modal.record?String(modal.record.farePaise/100):'20',active:modal.record?.active??true});
    if(modal.type==='stop')setDraft({name:modal.record?.name||'',locality:modal.record?.locality||'',active:modal.record?.active??true});
  },[modal]);
  const value=(key:string)=>String(draft[key]??'');const set=(key:string,v:string|boolean)=>setDraft(d=>({...d,[key]:v}));
  const titles={departure:'New departure',assign:'Assign driver',driver:isEdit?'Save changes':'Add driver',route:isEdit?'Edit route':'Add route',stop:isEdit?'Edit stop':'Add stop'};
  const buttons={departure:'Create departure',assign:'Save assignment',driver:isEdit?'Save changes':'Create driver',route:isEdit?'Save changes':'Create route',stop:isEdit?'Save changes':'Create stop'};
  const notices={departure:'Departure created',assign:'Driver assigned',driver:isEdit?'Changes saved':'Driver created',route:isEdit?'Changes saved':'Route created',stop:isEdit?'Changes saved':'Stop created'};
  const mutation=useMutation({mutationFn:async()=>{
    if(modal.type==='departure')return api('/operator/departures',{method:'POST',body:{routeId:value('routeId'),departureAt:new Date(`${value('departureAt')}:00+05:30`).toISOString(),durationMinutes:Number(value('durationMinutes')),capacity:Number(value('capacity')),...(value('driverId')!=='none'?{driverId:value('driverId')}:{})}});
    if(modal.type==='assign')return api(`/operator/departures/${modal.record.id}/assign`,{method:'POST',body:{driverId:value('driverId')}});
    if(modal.type==='driver')return api(modal.record?`/operator/drivers/${modal.record.userId}`:'/operator/drivers',{method:modal.record?'PATCH':'POST',body:modal.record?{active:draft.active,verified:draft.verified}:{name:value('name'),email:value('email'),password:value('password'),phone:value('phone'),vehicle:value('vehicle'),capacity:Number(value('capacity')),verified:draft.verified}});
    if(modal.type==='route')return api(modal.record?`/operator/routes/${modal.record.id}`:'/operator/routes',{method:modal.record?'PATCH':'POST',body:{fromStopId:value('fromStopId'),toStopId:value('toStopId'),farePaise:Math.round(Number(value('fare'))*100),active:draft.active}});
    return api(modal.record?`/operator/stops/${modal.record.id}`:'/operator/stops',{method:modal.record?'PATCH':'POST',body:{name:value('name'),locality:value('locality'),active:draft.active}});
  },onSuccess:()=>{success();toast.success(t(notices[modal.type]));close();},onError:e=>toast.error(e.message)});
  const field=(key:string,label:string,type='text',min?:number,max?:number)=><div className="field" key={key}><Label htmlFor={`op-${key}`}>{t(label)}</Label><Input id={`op-${key}`} type={type} value={value(key)} onChange={e=>set(key,e.target.value)} required min={min} max={max} step={key==='fare'?'0.01':undefined} minLength={key==='password'?10:undefined} maxLength={type==='text'?80:undefined}/></div>;
  const checkbox=(key:string,label:string)=><label className="checkbox-field" key={key}><input type="checkbox" checked={!!draft[key]} onChange={e=>set(key,e.target.checked)}/>{t(label)}</label>;
  return <Dialog open onOpenChange={o=>{if(!o&&!mutation.isPending)close();}}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>{t(titles[modal.type])}</DialogTitle><DialogDescription>{t('Local operations')}</DialogDescription></DialogHeader><form className="dialog-form mt-3" onSubmit={e=>{e.preventDefault();mutation.mutate();}}>
  {modal.type==='departure'&&<><Picker id="op-route" label="Route" value={value('routeId')} onChange={v=>set('routeId',v)} items={data.routes.filter(r=>r.active).map(r=>({value:r.id,label:`${t(r.pickup)} — ${t(r.destination)}`}))}/>{field('departureAt','Departure date and time','datetime-local')}{field('durationMinutes','Duration in minutes','number',10,180)}{field('capacity','Vehicle capacity','number',1,4)}<Picker id="op-driver" label="Driver" value={value('driverId')} onChange={v=>set('driverId',v)} items={[{value:'none',label:'Unassigned'},...data.drivers.filter(d=>d.active&&d.verified).map(d=>({value:d.userId,label:d.name}))]}/><p>{t('Times are shown in India Standard Time.')}</p></>}
  {modal.type==='assign'&&<Picker id="op-assign" label="Driver" value={value('driverId')} onChange={v=>set('driverId',v)} items={data.drivers.filter(d=>d.active&&d.verified).map(d=>({value:d.userId,label:d.name}))}/>}
  {modal.type==='driver'&&(modal.record?<>{checkbox('active','Active')}{checkbox('verified','Verified by operator')}</>:<>{field('name','Full name')}{field('email','Email','email')}{field('password','Password','password')}{field('phone','Mobile number','tel')}{field('vehicle','Vehicle registration')}{field('capacity','Vehicle capacity','number',1,4)}{checkbox('verified','Verified by operator')}</>)}
  {modal.type==='route'&&<><Picker id="op-from" label="Pickup point" value={value('fromStopId')} onChange={v=>set('fromStopId',v)} items={data.stops.filter(s=>s.active).map(s=>({value:s.id,label:s.name}))}/><Picker id="op-to" label="Destination" value={value('toStopId')} onChange={v=>set('toStopId',v)} items={data.stops.filter(s=>s.active).map(s=>({value:s.id,label:s.name}))}/>{field('fare','Fare per seat (₹)','number',1,1000)}{checkbox('active','Active')}</>}
  {modal.type==='stop'&&<>{field('name','Stop name')}{field('locality','Locality')}{checkbox('active','Active')}</>}
  {mutation.error&&<div className="form-error" role="alert">{mutation.error.message}</div>}<footer><Button variant="outline" type="button" disabled={mutation.isPending} onClick={close}>{t('Cancel')}</Button><Button type="submit" disabled={mutation.isPending}>{mutation.isPending?t('Please wait'):t(buttons[modal.type])}</Button></footer>
  </form></DialogContent></Dialog>;
}
