'use client';
import {useState,useEffect,useRef} from 'react';
import {useQuery,useInfiniteQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {MapPin,Users,Minus,Plus,ShieldCheck,Clock,Wallet,BusFront,Phone,Info} from 'lucide-react';
import {toast} from 'sonner';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Picker,RouteLine,TripTime,Status,Empty,LoadingCards,ErrorState} from './shared';
import {api,money,time,date,localDate} from '@/lib/api';
import {useLanguage} from '@/lib/i18n';
import type {UserDTO,StopDTO,RouteDTO,DepartureDTO,BookingDTO} from '@saathi/contracts';
export function Rider({user,view,navigate,signIn,demo}:{user:UserDTO|null;view:string;navigate:(v:string)=>void;signIn:()=>void;demo:boolean}){
  const {t}=useLanguage();const qc=useQueryClient();const [pickup,setPickup]=useState('');const [destination,setDestination]=useState('');const [travelDate,setTravelDate]=useState(localDate());const [seats,setSeats]=useState(1);const [selected,setSelected]=useState<DepartureDTO|null>(null);const [confirm,setConfirm]=useState(false);const [cancel,setCancel]=useState<BookingDTO|null>(null);const [tab,setTab]=useState('upcoming');const [contactPhone,setContactPhone]=useState(user?.phone||(demo?'9000000099':''));
  const [applied,setApplied]=useState<{from:string;to:string;date:string}|null>(null);const requestKey=useRef('');
  const stops=useQuery({queryKey:['stops'],queryFn:()=>api<{stops:StopDTO[]}>('/stops')});
  const routes=useQuery({queryKey:['routes'],queryFn:()=>api<{routes:RouteDTO[]}>('/routes')});
  const from=pickup||routes.data?.routes[0]?.fromStopId||'';
  const matchingRoutes=routes.data?.routes.filter(r=>r.fromStopId===from)||[];
  const to=destination||matchingRoutes[0]?.toStopId||'';
  const filters=applied||{from,to,date:travelDate};
  const departures=useQuery({queryKey:['departures',filters],queryFn:()=>api<{departures:DepartureDTO[]}>(`/departures?${new URLSearchParams(filters)}`),enabled:!!filters.from&&!!filters.to,refetchInterval:view==='book'?30000:false});
  const bookings=useInfiniteQuery({queryKey:['bookings',user?.id],queryFn:({pageParam})=>api<{bookings:BookingDTO[];page:number;hasMore:boolean}>(`/bookings?page=${pageParam}&limit=30`),initialPageParam:1,getNextPageParam:last=>last.hasMore?last.page+1:undefined,enabled:!!user&&view==='rides',refetchInterval:view==='rides'?30000:false});
  useEffect(()=>{if(user&&selected&&!confirm)setConfirm(true);},[user]); // Preserve the chosen departure across sign-in.
  const book=useMutation({mutationFn:()=>api<{booking:BookingDTO}>('/bookings',{method:'POST',body:{departureId:selected!.id,seats,contactPhone,idempotencyKey:requestKey.current}}),onSuccess:()=>{qc.invalidateQueries({queryKey:['departures']});qc.invalidateQueries({queryKey:['bookings',user?.id]});setConfirm(false);setSelected(null);navigate('rides');setTab('upcoming');toast.success(t('Booking confirmed'));},onError:e=>toast.error(e.message)});
  const cancellation=useMutation({mutationFn:()=>api(`/bookings/${cancel!.id}/cancel`,{method:'POST',body:{}}),onSuccess:()=>{qc.invalidateQueries({queryKey:['bookings',user?.id]});qc.invalidateQueries({queryKey:['departures']});setCancel(null);toast.success(t('Booking cancelled'));},onError:e=>toast.error(e.message)});
  function choose(d:DepartureDTO){setSelected(d);requestKey.current=crypto.randomUUID();book.reset();if(user)setConfirm(true);else signIn();}
  const available=(departures.data?.departures||[]).filter(d=>d.availableSeats>=seats);
  const allBookings=bookings.data?.pages.flatMap(p=>p.bookings)||[];
  const filteredBookings=allBookings.filter(b=>tab==='upcoming'?b.status==='confirmed':b.status!=='confirmed');
  return <>
  {view==='rides'?<><div className="page-heading"><h1>{t('My rides')}</h1><p>{t('Your next ride starts here.')}</p></div>{!user?<Empty title="Sign in to book"><Button onClick={signIn}>{t('Sign in')}</Button></Empty>:<><Tabs value={tab} onValueChange={setTab} className="segmented"><TabsList className="h-12"><TabsTrigger value="upcoming" className="min-h-10 px-5">{t('Upcoming')}</TabsTrigger><TabsTrigger value="history" className="min-h-10 px-5">{t('History')}</TabsTrigger></TabsList></Tabs>{bookings.isPending?<LoadingCards/>:bookings.error?<ErrorState error={bookings.error} retry={()=>bookings.refetch()}/>:filteredBookings.length?<div className="list-grid">{filteredBookings.map(b=><article className="booking-card" key={b.id}><header><span className="reference">{b.reference}</span><Status value={b.status}/></header><RouteLine departure={b.departure}/><TripTime departure={b.departure}/><div className="driver-meta"><BusFront size={15}/>{b.departure.driverName} {b.departure.vehicle&&<span>• {b.departure.vehicle}</span>}</div><div className="summary-row"><span>{b.seats} {t(b.seats===1?'Seat':'Seats')}</span><strong>{money(b.totalPaise)}</strong></div><p className="subtext mt-3">{t(b.cashCollected?'Cash recorded':'Pay the driver in cash')}</p><footer>{b.departure.driverPhone&&b.status==='confirmed'?<Button variant="outline" asChild><a href={`tel:${b.departure.driverPhone}`}><Phone size={16}/>{t('Call driver')}</a></Button>:<span className="subtext">{date(b.createdAt)}</span>}{b.status==='confirmed'&&b.departure.status==='scheduled'&&new Date(b.departure.departureAt)>new Date()&&!b.cashCollected&&<Button variant="ghost" onClick={()=>{setCancel(b);cancellation.reset();}}>{t('Cancel booking')}</Button>}</footer></article>)}</div>:<Empty title={tab==='upcoming'?'No bookings yet':'No history yet'} description="Your next ride starts here."><Button variant="outline" onClick={()=>navigate('book')}>{t('Browse rides')}</Button></Empty>}{bookings.hasNextPage&&<Button variant="outline" className="mt-5" onClick={()=>bookings.fetchNextPage()} disabled={bookings.isFetchingNextPage}>{t('Load more')}</Button>}</>}</>:<div className="main-booking"><div className="page-heading"><div className="eyebrow"><MapPin size={15}/>{t('Rampur & nearby towns')}{demo&&<span className="demo-tag">{t('Demo service')}</span>}</div><h1>{t('Where are you headed?')}</h1><p>{t('Shared rides. Familiar routes. Fair fares.')}</p></div><div className="booking-grid"><div>
  <form className="booking-panel" onSubmit={e=>{e.preventDefault();setApplied({from,to,date:travelDate});}}><div className="search-fields"><div className="route-fields"><Picker id="pickup" label="Pickup point" value={from} onChange={value=>{setPickup(value);setDestination('');setApplied(null);}} items={(stops.data?.stops||[]).filter(s=>routes.data?.routes.some(r=>r.fromStopId===s.id)).map(s=>({value:s.id,label:s.name}))}/><Picker id="destination" label="Destination" value={to} onChange={value=>{setDestination(value);setApplied(null);}} items={matchingRoutes.map(r=>({value:r.toStopId,label:r.destination}))}/></div><div className="date-seats"><div className="field"><Label htmlFor="travel-date">{t('Departure date')}</Label><div className="date-options"><Button type="button" variant="outline" className={travelDate===localDate()?'selected':''} onClick={()=>{setTravelDate(localDate());setApplied(null);}}>{t('Today')}</Button><Button type="button" variant="outline" className={travelDate===localDate(1)?'selected':''} onClick={()=>{setTravelDate(localDate(1));setApplied(null);}}>{t('Tomorrow')}</Button></div><Input className="date-input" id="travel-date" type="date" value={travelDate} min={localDate()} max={localDate(7)} onChange={e=>{setTravelDate(e.target.value);setApplied(null);}} required/></div><div className="field"><Label>{t('Passengers')}</Label><div className="passenger-control"><Button type="button" variant="ghost" size="icon" aria-label={t('Remove passenger')} disabled={seats===1} onClick={()=>setSeats(seats-1)}><Minus size={17}/></Button><strong className="flex items-center gap-2"><Users size={17}/>{seats}</strong><Button type="button" variant="ghost" size="icon" aria-label={t('Add passenger')} disabled={seats===4} onClick={()=>setSeats(seats+1)}><Plus size={17}/></Button></div></div></div></div><Button className="search-submit" type="submit" disabled={!from||!to||departures.isFetching}><MapPin size={17}/>{t('Find rides')}</Button></form>
  <div className="rides-heading" aria-live="polite"><h2>{t('Available rides')}</h2><span>{available.length} {t('rides')}</span></div>
  {(stops.error||routes.error||departures.error)?<ErrorState error={stops.error||routes.error||departures.error} retry={()=>{stops.refetch();routes.refetch();departures.refetch();}}/>:(stops.isPending||routes.isPending||(departures.isPending&&!!from&&!!to))?<LoadingCards/>:available.length?<div className="rides-list">{available.map(d=><article className="ride-card" key={d.id}><div className="ride-card-head"><div><strong className="departure-time">{time(d.departureAt)}</strong><span className="departure-date">{date(d.departureAt)}</span></div><span className="seat-label">{d.availableSeats} {t(d.availableSeats===1?'seat left':'seats left')}</span></div><RouteLine departure={d}/><div className="driver-meta"><BusFront size={15}/><span>{d.driverName}</span><span>•</span><span>{Math.round((new Date(d.endAt).getTime()-new Date(d.departureAt).getTime())/60000)} {t('min')}</span></div><footer className="ride-footer"><span className="fare">{money(d.farePaise*seats)}<small>{seats===1?t('per seat'):`${t('Total fare')} · ${seats} ${t('Seats')}`}</small></span><Button onClick={()=>choose(d)}>{t('Book ride')}</Button></footer></article>)}</div>:<Empty title="No rides found" description="Try another route or date."/>}
  </div><aside className="side-note"><div className="note-block"><h2>{t('Simple from start to stop')}</h2>{[{icon:Clock,title:'Meet at the pickup point',body:'Arrive five minutes before departure.'},{icon:Wallet,title:'One fare, no bargaining',body:'The price you see is your total fare.'},{icon:Users,title:'A shared ride',body:'Travel with others on the same route.'}].map(tip=><div className="tip" key={tip.title}><span className="tip-icon"><tip.icon size={19}/></span><div><strong>{t(tip.title)}</strong><p>{t(tip.body)}</p></div></div>)}</div><div className="service-note"><ShieldCheck size={20} className="shrink-0"/><p>{t('Seat availability may change before confirmation.')}</p></div>{demo&&<div className="service-note"><Info size={18} className="shrink-0"/><p>{t('No actual transport is dispatched.')}</p></div>}</aside></div></div>}
  <Dialog open={confirm} onOpenChange={o=>{if(!book.isPending){setConfirm(o);if(!o)setSelected(null);}}}><DialogContent><DialogHeader><DialogTitle>{t('Review booking')}</DialogTitle><DialogDescription>{t('Your seat is reserved after confirmation.')}</DialogDescription></DialogHeader>{selected&&<div className="dialog-form mt-3"><RouteLine departure={selected}/><TripTime departure={selected}/><div><div className="summary-row"><span>{t('Passengers')}</span><strong>{seats}</strong></div><div className="summary-row"><span>{t('Total fare')}</span><strong>{money(selected.farePaise*seats)}</strong></div></div><div className="field"><Label htmlFor="booking-phone">{t('Mobile number')}</Label><Input id="booking-phone" type="tel" inputMode="numeric" autoComplete="tel-national" value={contactPhone} onChange={e=>setContactPhone(e.target.value)} maxLength={10} required disabled={book.isPending}/></div><div className="info-banner"><Wallet size={19}/>{t('Pay the driver in cash')}</div>{book.error&&<div className="form-error" role="alert">{book.error.message}</div>}<Button disabled={book.isPending||offline()||!/^[6-9]\d{9}$/.test(contactPhone)} onClick={()=>book.mutate()}>{book.isPending?t('Please wait'):t('Confirm booking')}</Button></div>}</DialogContent></Dialog>
  <AlertDialog open={!!cancel} onOpenChange={o=>{if(!o&&!cancellation.isPending)setCancel(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t('Cancel booking')}</AlertDialogTitle><AlertDialogDescription>{t('Cancellation returns your seats to the timetable.')}</AlertDialogDescription></AlertDialogHeader>{cancellation.error&&<p className="form-error">{cancellation.error.message}</p>}<AlertDialogFooter><AlertDialogCancel disabled={cancellation.isPending}>{t('Keep booking')}</AlertDialogCancel><AlertDialogAction disabled={cancellation.isPending} onClick={e=>{e.preventDefault();cancellation.mutate();}}>{t('Yes, cancel booking')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </>;
}
function offline(){return typeof navigator!=='undefined'&&!navigator.onLine;}
